# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - pyrus install http://phptal.org/latest.tar.gz
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

# Script to run tests
script: 
  - phpunit
  - phpcs --standard=PSR2 --extensions=php src/ tests/
